#!/usr/bin/env bash

add-apt-repository -y ppa:webupd8team/java
apt-get update

# Accept Oracle Java license
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

# install
apt-get install -y git vim tmux oracle-java8-installer

